### ISSUE TITLE
Don't forget to update for 2.207

### ISSUE THREAD

**Issue by DragosDobrican** [user95401/Robots-Directional-Rotation#2]

**Comment by lil2kki** [comment]
i was banned on geode for no reason so update will never be uploaded to geode server

update up to sdk v4 for gd 2.2074 already released, install it manually
https://github.com/user95401/Robots-Directional-Rotation/releases/tag/v1.3.1

download .geode file and use this button
![image](https://github.com/user-attachments/assets/cbe9aa6b-1752-4e84-b06a-d8e76e9affda)

**Comment by DragosDobrican** [comment]
Oh, that's sad, how did you get banned anyway?
